/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * VentanaListadoCompras.java
 *
 * Created on 16-jun-2010, 15:29:53
 */

package vista;

import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import controlador.ControladorCompras;
import modelo.Compras;

/**
 *
 * @author gustavo
 */
public class VentanaListadoCompras extends javax.swing.JInternalFrame {

    ControladorCompras controladorCompra = new ControladorCompras();
    /** Creates new form VentanaListadoCompras */
    public VentanaListadoCompras() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fechaDesdeTf = new javax.swing.JFormattedTextField();
        listar = new javax.swing.JButton();
        fechaHastaTf = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();

        setClosable(true);

        fechaDesdeTf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));

        listar.setText("Listar");
        listar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarActionPerformed(evt);
            }
        });

        fechaHastaTf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));

        jLabel1.setText("Desde Fecha:");
        jLabel1.setFocusable(false);

        jLabel2.setText("Hasta Fecha:");
        jLabel2.setFocusable(false);

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Fecha", "NroCbte", "Proveedor", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabla);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 539, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fechaDesdeTf, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fechaHastaTf, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(listar, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(fechaHastaTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(listar)
                    .addComponent(fechaDesdeTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarActionPerformed
        if (fechaDesdeTf.getValue() == null) {
            JOptionPane.showMessageDialog(this,
                    "La fecha de inicio no puede ser nula",
                    "Formato No Válido", JOptionPane.ERROR_MESSAGE);
            fechaDesdeTf.requestFocus();
            return;
        } else if (fechaHastaTf.getValue() == null) {
            JOptionPane.showMessageDialog(this,
                    "La fecha de fin no puede ser nula",
                    "Formato No Válido", JOptionPane.ERROR_MESSAGE);
            fechaHastaTf.requestFocus();
            return;
        }

        if (((Date)fechaDesdeTf.getValue()).compareTo((Date)fechaHastaTf.getValue()) > 0) {
            JOptionPane.showMessageDialog(this,
                    "La fecha de inicio no puede ser mayor a la fecha de fin",
                    "Formato No Válido", JOptionPane.ERROR_MESSAGE);
            fechaDesdeTf.requestFocus();
            return;
        }

        List<Compras> compras = controladorCompra.listar(
                (Date)fechaDesdeTf.getValue(), (Date) fechaHastaTf.getValue());

        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");

        DefaultTableModel dm = (DefaultTableModel)tabla.getModel();
        dm.setRowCount(0);
        for (Compras v : compras) {
            dm.addRow(new Object[] {
                sdf.format(v.getFecha()),
                v.getId(),
                v.getProveedoresId().getNombre(),
                v.getTotal()});
        }
    }//GEN-LAST:event_listarActionPerformed

    private void tablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMouseClicked
        if (evt.getClickCount() == 2) {
            Integer NroCbte = (Integer)(tabla.getValueAt(tabla.getSelectedRow(), 1));
            Compras v = ControladorCompras.mostrar(NroCbte);
            VentanaMostrarCompra vmv = new VentanaMostrarCompra(v);
            this.getParent().add(vmv);
            vmv.show();
        }
}//GEN-LAST:event_tablaMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField fechaDesdeTf;
    private javax.swing.JFormattedTextField fechaHastaTf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton listar;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables

}
