/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * VentanaMostrarCompra.java
 *
 * Created on 16-jun-2010, 15:36:08
 */

package vista;

import modelo.DetallesCompras;
import modelo.DetallesVentas;
import modelo.Ventas;
/**
 *
 * @author gustavo
 */
public class VentanaMostrarVenta extends javax.swing.JInternalFrame {

    /** Creates new form VentanaMostrarCompra */
    public VentanaMostrarVenta(Ventas v) {
        initComponents();

        //definicion del ancho  de los columnas
        detalles.getColumnModel().getColumn(0).setPreferredWidth(60);
        detalles.getColumnModel().getColumn(1).setPreferredWidth(120);
        detalles.getColumnModel().getColumn(2).setPreferredWidth(60);
        detalles.getColumnModel().getColumn(3).setPreferredWidth(60);
        detalles.getColumnModel().getColumn(4).setPreferredWidth(60);

        nroCbteTf.setText(v.getId().toString());
        fechaTf.setValue(v.getFecha());
        rucCiTf.setText(v.getClientesId().getRuc());
        codClienteTf.setText(Integer.toString(v.getClientesId().getId()));
        nombreTf.setText(v.getClientesId().getNombre());
        direccionTf.setText(v.getClientesId().getDireccion());

        int i=0;
        for(DetallesVentas detalle : v.getDetallesVentasCollection()){
            detalles.getModel().setValueAt(detalle.getProductos().getId(), i, 0);
            detalles.getModel().setValueAt(detalle.getProductos().getDescripcion(), i, 1);
            detalles.getModel().setValueAt(detalle.getCantidad(), i, 2);
            detalles.getModel().setValueAt(detalle.getProductos().getPrecio(), i, 3);
            detalles.getModel().setValueAt(detalle.getProductos().getPrecio()*detalle.getCantidad(), i, 4);
            i++;
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        codClienteTf = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        detalles = new javax.swing.JTable();
        codProveedorLabel = new javax.swing.JLabel();
        nroCbteTf = new javax.swing.JTextField();
        nroCbteLabel = new javax.swing.JLabel();
        fechaTf = new javax.swing.JFormattedTextField();
        fechaLabel = new javax.swing.JLabel();
        direccionTf = new javax.swing.JTextField();
        nombreTf = new javax.swing.JTextField();
        direccionProveedorLabel = new javax.swing.JLabel();
        rucCiLabel = new javax.swing.JLabel();
        nombreProveedorLabel = new javax.swing.JLabel();
        rucCiTf = new javax.swing.JTextField();

        setClosable(true);

        codClienteTf.setEnabled(false);

        detalles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Descripcion", "Cantidad", "Precio", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        detalles.setEnabled(false);
        jScrollPane1.setViewportView(detalles);

        codProveedorLabel.setText("Código Cliente");

        nroCbteTf.setEnabled(false);

        nroCbteLabel.setText("Nro. Cbte:");

        fechaTf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));
        fechaTf.setEnabled(false);

        fechaLabel.setText("Fecha (dd/mm/aaaa):");

        direccionTf.setEditable(false);

        nombreTf.setEditable(false);

        direccionProveedorLabel.setText("Dirección:");

        rucCiLabel.setText("Ruc/CI:");

        nombreProveedorLabel.setText("Nombre:");

        rucCiTf.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 591, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fechaLabel)
                            .addComponent(codProveedorLabel)
                            .addComponent(nombreProveedorLabel)
                            .addComponent(direccionProveedorLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fechaTf, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(codClienteTf, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rucCiLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(rucCiTf, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(nroCbteLabel)
                                        .addGap(10, 10, 10)
                                        .addComponent(nroCbteTf, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(nombreTf, javax.swing.GroupLayout.DEFAULT_SIZE, 477, Short.MAX_VALUE)
                            .addComponent(direccionTf, javax.swing.GroupLayout.DEFAULT_SIZE, 477, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(fechaTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fechaLabel)
                    .addComponent(nroCbteTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nroCbteLabel))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(codProveedorLabel)
                    .addComponent(codClienteTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rucCiLabel)
                    .addComponent(rucCiTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreProveedorLabel)
                    .addComponent(nombreTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(direccionProveedorLabel)
                    .addComponent(direccionTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField codClienteTf;
    private javax.swing.JLabel codProveedorLabel;
    private javax.swing.JTable detalles;
    private javax.swing.JLabel direccionProveedorLabel;
    private javax.swing.JTextField direccionTf;
    private javax.swing.JLabel fechaLabel;
    private javax.swing.JFormattedTextField fechaTf;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nombreProveedorLabel;
    private javax.swing.JTextField nombreTf;
    private javax.swing.JLabel nroCbteLabel;
    private javax.swing.JTextField nroCbteTf;
    private javax.swing.JLabel rucCiLabel;
    private javax.swing.JTextField rucCiTf;
    // End of variables declaration//GEN-END:variables

}
